apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
  namespace: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-httpd
  template:
    metadata:
      labels:
        app: simple-httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: httpd-index
              mountPath: /usr/local/apache2/htdocs/index.html
              subPath: index.html
      volumes:
        - name: httpd-index
          configMap:
            name: httpd-index
